#
# Mode de compilation
#	Valeurs possibles : yes , no
DEBUG=yes

#
# Option compilation
#
CC = gcc
CCOBJ=$(CC) -c

#
# Gestion des drapeaux
#
CDEBUG=
ifeq ($(DEBUG),yes)
	 CDEBUG = -g
else
	 CDEBUG =
endif
CFLAGS = -Wall -g
