#
# Mode de compilation
#	Valeurs possibles : yes , no
DEBUG=yes

#
# Option compilation
#
CC = gcc
CCOBJ=$(CC) -c

#
# Gestion des drapeaux
#
CDEBUG=
ifeq ($(DEBUG),yes)
	 CDEBUG = -g
else
	 CDEBUG =
endif

ifeq ($(OS),Windows_NT)
	CFLAGS = -L sdl/lib -I sdl/include -lSDL2main -lSDL2 -lSDL2 image -lSDL2 ttf -Wall $(CDEBUG)
else
	CFLAGS = -L ~/sdl/lib -I ~/sdl/include -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -Wall $(CDEBUG)
endif